spring:
    application:
        name: springboot
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    jwt:
        secret: dmgaboiqgnowgnaiogioaehfeoigvhbdmcmvalkngiedorfghoiergyhieersdfhiowmweqazpzodmfs
    security:
        oauth2:
            client:
                registration:
                    google:

    thymeleaf:
        cache: false
        check-template-location: false